### ISSUE TITLE
Do you have a plan for this project?

### ISSUE THREAD

**Issue by prepare** [SpacialCircumstances/CottonRenderer#2]
Hello, 

I download the original code from the link (https://www.davrous.com/2013/06/13/tutorial-series-learning-how-to-write-a-3d-soft-engine-from-scratch-in-c-typescript-or-javascript),

and modify it to make it runs on WindowForms.
 
---

![monkey1](https://user-images.githubusercontent.com/7447159/35785200-41f0ee58-0a51-11e8-81ac-494ac064e874.png)

_[step 6](https://www.davrous.com/2013/07/18/tutorial-part-6-learning-how-to-write-a-3d-software-engine-in-c-ts-or-js-texture-mapping-back-face-culling-webgl/),WinForms, un-optimized, avg 19ms per frame, 52 fps_

---

![monkey2](https://user-images.githubusercontent.com/7447159/35785386-9483be1a-0a52-11e8-965b-22fedafbded3.png)
_compare with the original js version on FireFox 58_

---
I check that the CottonRenderer is not in this step.

Do you have a plan for this project?

**Comment by SpacialCircumstances** [comment]
CottonRenderer does not support textures and shading because I wanted to leave the choice to use those to the user, which is not possible with the tutorial code.
I don’t really have a plan- The project as it is seems to be in a dead end. The current codebase does not allow a lot of things I would like it to, for example:
1. .Net Standard
2. Get rid of DirectX
3. Textures, custom shaders etc.
4. Multithreading
...

To support all that I would have to do a full rewrite, and I haven’t found a reason to do that yet.

**Comment by prepare** [comment]
Thank you :)
